/**
 * Tests for frontend/src/lib/presets/classPresets.js
 *
 * Run with: node frontend/tests/presets.test.mjs
 *
 * fixtures/python_reference.json was generated by executing the real Python
 * module (api/app/data/class_presets.py) and capturing the exact router
 * responses, so the parity checks below compare number-for-number and in
 * key order.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  CLASS_PRESETS,
  ROLE_TEMPLATES,
  listAllClasses,
  listRolesForClass,
  getClassPreset,
  getElementPreferencesFromPreset,
  getClassDetails,
} from '../src/lib/presets/classPresets.js';

const here = dirname(fileURLToPath(import.meta.url));
const REF = JSON.parse(readFileSync(join(here, 'fixtures', 'python_reference.json'), 'utf-8'));

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed += 1;
    console.log(`  ok - ${name}`);
  } catch (err) {
    failed += 1;
    console.error(`  FAIL - ${name}`);
    console.error(`    ${err.message}`);
  }
}

function assertEqual(actual, expected, label = 'value') {
  if (actual !== expected) {
    throw new Error(`${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
}

function assertTrue(cond, label = 'condition') {
  if (!cond) throw new Error(`${label}: expected truthy`);
}

/** Exact structural equality: values, nesting AND key order. */
function assertJsonExact(actual, expected, label = 'response') {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a !== e) {
    let i = 0;
    while (i < Math.min(a.length, e.length) && a[i] === e[i]) i += 1;
    const ctx = (s) => s.slice(Math.max(0, i - 60), i + 60);
    throw new Error(`${label} mismatch at char ${i}:\n    expected ...${ctx(e)}...\n    actual   ...${ctx(a)}...`);
  }
}

// ---------------------------------------------------------------------------
console.log('data integrity');

test('class count matches Python (18 classes)', () => {
  assertEqual(Object.keys(CLASS_PRESETS).length, REF.class_count, 'class count');
  assertEqual(Object.keys(CLASS_PRESETS).length, 18, 'class count literal');
});

test('ROLE_TEMPLATES matches Python exactly (GET /presets/roles)', () => {
  assertJsonExact(ROLE_TEMPLATES, REF.role_templates, 'ROLE_TEMPLATES');
});

test('every class ported number-for-number (full CLASS_PRESETS vs Python details endpoint)', () => {
  for (const classId of Object.keys(CLASS_PRESETS)) {
    // The details endpoint returns CLASS_PRESETS[class] verbatim; the fixture
    // "classes" list pins ids/names/roles, ecaflip is pinned in full below.
    const info = REF.classes.find((c) => c.id === classId);
    assertTrue(info, `${classId} present in Python`);
    assertEqual(CLASS_PRESETS[classId].name, info.name, `${classId}.name`);
    assertEqual(CLASS_PRESETS[classId].icon, info.icon, `${classId}.icon`);
    assertEqual(CLASS_PRESETS[classId].primary_role, info.primary_role, `${classId}.primary_role`);
    assertJsonExact(Object.keys(CLASS_PRESETS[classId].roles), info.roles, `${classId}.roles keys`);
  }
});

test('spot-check weights number-for-number', () => {
  assertEqual(CLASS_PRESETS.iop.roles.dps_melee.weights.Melee_Mastery, 9.0, 'iop dps_melee Melee_Mastery');
  assertEqual(CLASS_PRESETS.iop.roles.berserker.weights.Berserk_Mastery, 10.0, 'iop berserker Berserk_Mastery');
  assertEqual(CLASS_PRESETS.ecaflip.roles.dps_crit.weights.Critical_Hit, 10.0, 'ecaflip dps_crit Critical_Hit');
  assertEqual(CLASS_PRESETS.feca.roles.tank.weights.Armor_Given, 5.0, 'feca tank Armor_Given');
  assertEqual(CLASS_PRESETS.feca.roles.tank.weights.Critical_Resistance, 6.0, 'feca tank Critical_Resistance');
  assertEqual(CLASS_PRESETS.huppermage.roles.dps_quad.weights.Elemental_Mastery, 8.0, 'huppermage dps_quad Elemental_Mastery');
  assertEqual(CLASS_PRESETS.enutrof.roles.support_mp.weights.Prospecting, 5.0, 'enutrof support_mp Prospecting');
  assertEqual(CLASS_PRESETS.sram.roles.assassin.weights.Rear_Mastery, 10.0, 'sram assassin Rear_Mastery');
  assertEqual(CLASS_PRESETS.eniripsa.roles.healer.weights.Healing_Mastery, 10.0, 'eniripsa healer Healing_Mastery');
  assertEqual(CLASS_PRESETS.sacrier.roles.berserker.weights.HP, 8.0, 'sacrier berserker HP');
  assertEqual(CLASS_PRESETS.cra.roles.sniper.weights.Distance_Mastery, 10.0, 'cra sniper Distance_Mastery');
  assertEqual(CLASS_PRESETS.rogue.roles.bomber.weights.Critical_Mastery, 9.0, 'rogue bomber Critical_Mastery');
  assertEqual(ROLE_TEMPLATES.tank.weights.Force_Of_Will, 6.0, 'tank template Force_Of_Will');
  assertEqual(ROLE_TEMPLATES.healer.weights.Wisdom, 3.0, 'healer template Wisdom');
  assertEqual(ROLE_TEMPLATES.dps_distance.weights.Range, 7.0, 'dps_distance template Range');
});

test('spot-check element lists', () => {
  assertJsonExact(CLASS_PRESETS.huppermage.roles.dps_quad.elements, ['Fire', 'Water', 'Earth', 'Air'], 'huppermage quad elements');
  assertJsonExact(CLASS_PRESETS.eniripsa.roles.healer.elements, ['Water'], 'eniripsa healer elements');
  assertJsonExact(CLASS_PRESETS.masqueraider.roles.dps_versatile.elements, ['Fire', 'Air', 'Water'], 'masq versatile elements');
  assertJsonExact(CLASS_PRESETS.osamodas.roles.summoner.elements, ['Fire', 'Earth', 'Water'], 'osamodas summoner elements');
});

// ---------------------------------------------------------------------------
console.log('listAllClasses (GET /presets/classes)');

test('matches Python response exactly', () => {
  assertJsonExact(listAllClasses(), REF.classes, 'listAllClasses');
});

// ---------------------------------------------------------------------------
console.log('listRolesForClass (GET /presets/classes/{class}/roles)');

test('iop roles match Python exactly (is_primary flags included)', () => {
  assertJsonExact(listRolesForClass('iop'), REF.roles_iop, 'roles_iop');
});

test('class name is case-insensitive (FECA)', () => {
  assertJsonExact(listRolesForClass('FECA'), REF.roles_feca, 'roles_feca');
});

test('unknown class returns []', () => {
  assertJsonExact(listRolesForClass('nope'), [], 'roles_unknown');
});

// ---------------------------------------------------------------------------
console.log('getClassPreset (GET /presets/classes/{class}/preset)');

test('iop default role (primary dps_melee) matches Python', () => {
  assertJsonExact(getClassPreset('iop'), REF.preset_iop_default, 'preset_iop_default');
});

test('iop berserker role matches Python', () => {
  assertJsonExact(getClassPreset('iop', 'berserker'), REF.preset_iop_berserker, 'preset_iop_berserker');
});

test('osamodas default falls back to support ROLE_TEMPLATE weights (primary role not in class roles)', () => {
  assertJsonExact(getClassPreset('osamodas'), REF.preset_osamodas_default, 'preset_osamodas_default');
  // sanity: those are the support template weights with default element prefs
  assertJsonExact(getClassPreset('osamodas').weights, ROLE_TEMPLATES.support.weights, 'osamodas weights = support template');
});

test('sram default falls back to dps_melee ROLE_TEMPLATE weights', () => {
  assertJsonExact(getClassPreset('sram'), REF.preset_sram_default, 'preset_sram_default');
});

test('huppermage dps_quad matches Python', () => {
  assertJsonExact(getClassPreset('huppermage', 'dps_quad'), REF.preset_hupper_quad, 'preset_hupper_quad');
});

test('explicit role template fallback (iop + tank)', () => {
  assertJsonExact(getClassPreset('iop', 'tank'), REF.preset_iop_tank_template, 'preset_iop_tank_template');
});

test('unknown class returns fallback shape {weights:{}, default element prefs}', () => {
  assertJsonExact(getClassPreset('wizard'), REF.preset_unknown_class, 'preset_unknown_class');
  assertJsonExact(getClassPreset('wizard'), {
    weights: {},
    damage_preferences: ['Fire', 'Water', 'Earth', 'Air'],
    resistance_preferences: ['Fire', 'Water', 'Earth', 'Air'],
  }, 'fallback literal');
});

test('unknown role (not a template either) returns fallback shape', () => {
  assertJsonExact(getClassPreset('iop', 'totally_fake'), REF.preset_iop_badrole, 'preset_iop_badrole');
});

// ---------------------------------------------------------------------------
console.log('getElementPreferencesFromPreset');

test('eniripsa (Water primary) completes remaining elements in order', () => {
  assertJsonExact(getElementPreferencesFromPreset('eniripsa'), REF.prefs_eniripsa, 'prefs_eniripsa');
  assertJsonExact(getElementPreferencesFromPreset('eniripsa')[0], ['Water', 'Fire', 'Earth', 'Air'], 'eniripsa damage prefs');
});

test('huppermage dps_quad returns all four in role order', () => {
  assertJsonExact(getElementPreferencesFromPreset('huppermage', 'dps_quad'), REF.prefs_hupper_quad, 'prefs_hupper_quad');
});

test('unknown class returns default order for both tuples', () => {
  assertJsonExact(getElementPreferencesFromPreset('zzz'), REF.prefs_unknown, 'prefs_unknown');
});

// ---------------------------------------------------------------------------
console.log('getClassDetails (GET /presets/classes/{class})');

test('ecaflip full details match Python exactly', () => {
  assertJsonExact(getClassDetails('ecaflip'), REF.details_ecaflip, 'details_ecaflip');
});

test('case-insensitive lookup (ECAFLIP)', () => {
  assertJsonExact(getClassDetails('ECAFLIP'), REF.details_ecaflip, 'details_ecaflip upper');
});

test('unknown class returns {error: "Class not found"}', () => {
  assertJsonExact(getClassDetails('unknown_class'), { error: 'Class not found' }, 'details_unknown');
  assertJsonExact(getClassDetails('unknown_class'), REF.details_unknown, 'details_unknown fixture');
});

// ---------------------------------------------------------------------------
console.log('');
console.log(`${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
